### PR TITLE
Open links from new windows in an external browser

### LINKED ISSUE #60: External links open in new window from new window
- Gmail Desktop Version: latest
- OS Version: macOS Mojave

Steps to Reproduce:

1. Ctrl/cmd click on an email to open it in a new window
2. Click on an external link in the email (i.e. GitHub PR)
3. See how the link was opened in a new window, should be opened using `shell.openExternal` to open in a browser

### PR DESCRIPTION
**Pull request by markypython**
Fixes #60

### CODE REVIEW

**Comment by markypython** [comment]
Also fixes #62

**Comment by markypython** [comment]
Requires the electron downgrade in PR #58

**Comment by timche** [comment]
Please merge this PR rebased to keep the commits and don't squash them as this PR does multiple things, not only the PR title.

**Comment by markypython** [comment]
The `load` event fires before the buttons are created on the page.  In normal circumstances, it will find the button the first time, but it is possible in scenarios where the network is slow for it to take a little while.

I can update to element-ready if you would like, but I would recommend we wait on that until we have future needs for this functionality.  Then we can look into revamping it.

Thoughts?

**Comment by timche** [comment]
> I would recommend we wait on that until we have future needs for this functionality

With using `element-ready` I think we can improve the logic and make our code more readable and stable. I can also re-write it if you want.

**Comment by markypython** [comment]
So, I looked into the source of element-ready and it is using `requestAnimationFrame` to check if the element is present on the page.  This seems like overkill for what we need since that would be checking 60 times per second if the element is on the page.  I still think we should leave it as is, but if you disagree, let me know.

**Comment by timche** [comment]
I'm open to discuss the pros and cons. According to this [issue](https://github.com/sindresorhus/element-ready/issues/4), performance-wise it shouldn't be that CPU-intensive. Also using `setTimeout` can still leave a very small time-window open where the listener is not attached when clicked before, although the change might be quite low, but it can happen.

**Comment by timche** [comment]
By the way, I tried to checkout this PR, but the buttons aren't working for me. Anything I'm missing? I used the "In new window" button to open an email in a new window.

image

**Comment by timche** [comment]
Would you mind creating a separate PR for `Open links from new windows in an external browser` so we can get that in while we are discussing button listeners?

**Comment by markypython** [comment]
I'll open two new PRs for the separate branches.

**Pull request closed without merging**
