### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mskelton**
I just updated my system to the macOS Big Sur beta and the older version of Electron doesn't match the window style of Big Sur.  This will fix that by updating to the latest Electron version.

### CODE REVIEW

**Comment by timche** [comment]
This should also fix #204. Thanks a lot!

**Comment by mskelton** [comment]
@timche Looks like you just commented, but I'm assuming you are fine with me merging right?

**Comment by timche** [comment]
I was waiting for the build to complete so I can test it.

**Review by timche — APPROVED** [review]
LGTM

**Pull request merged**
