### PR TITLE
Capture notifications

### LINKED ISSUE #15: Sticky notifications not working
After you change the notification style for the Gmail desktop app to "Alert" (=sticky notification). When you receive a new mail, the notification disappears after a few seconds. I like it to be sticky.

### PR DESCRIPTION
**Pull request by markypython**
@timche I got started on the sticky notifications issue.  Making this a draft PR since it is only partially done, but the basic notifications handling is working.  I am capturing the web notifications and sending them to the Electron app so native notifications can be used.

Let me know your thoughts on the direction of this PR.

Fixes #15

### CODE REVIEW

**Comment by markypython** [comment]
@timche So, I am still unable to get the openEmail function to work since that is managed using the onclick method of the notification class.  Since that property get's added after the notification is instantiated and web notifications don't use a show notification, there isn't really a way to open the email using the notification click.  That said, we could use the title of the notification to search the emails in the inbox and if there is only one that matches, then we open that email.  The issue with that is of course the inconsistency when there is only one with that title and when there are multiple and the on click changing as a result.  I still think we should move forward with native notifications even if they only open the application, for the following reasons:

1. The current notifications don't support switching to "sticky" style (the whole thing that brought this issue up)
1. Clicking on the current notifications opens a new BrowserWindow which does not have the conditional logic as the main window of opening non Google links in the browser.  This causes issues when opening links to GitHub for example.

Thoughts on all this?  Sorry it got long :)

**Comment by markypython** [comment]
@timche If we move forward with this pr, then no because there shouldn't be any cases where a new window is opened.  Again, the tradeoff here is losing the onclick for the notification but gaining native notifications and not having a new window pop open when clicking on the notification.

**Comment by timche** [comment]
> there shouldn't be any cases where a new window is opened
That's different for me. I like to click on the notification to open the received email. That's an expected behaviour I know also from other email apps (e.g. Airmail).

**Comment by markypython** [comment]
I'm going to close this PR and take another go at trying to get it to work in all the right ways.

**Pull request closed without merging**
