### PR TITLE
Add .rpm package to existing linux build targets (fixes #91)

### LINKED ISSUE #91: Add support for RPM packages (for Linux)
I've seen that on the release tab there already is `.deb`, and from what I gathered it is generated by some generic tool you have integrated.  Could you also add support for `.rpm`?

### PR DESCRIPTION
**Pull request by cyfrost**
This fixes issue #91

### CODE REVIEW

**Comment by markypython** [comment]
@cyfrost Should we add `pacman`, `snap`, and `tar.bz2` as well?

**Comment by markypython** [comment]
@cyfrost I would also suggest adding the zip target for Windows as that was mentioned in #91

i.e.

```json
"win": {
  "target": [
    "nsis",
    "zip"
  ]
}
```

**Comment by cyfrost** [comment]
Updated build targets will be:

For Linux: `.deb`, `.rpm`, `.snap`, `.pacman`, `.AppImage`, `.tar.bz2`

For Windows: `.nsis`, `.zip`

Although, Electron Builder did warn me about this:

image

**Comment by markypython** [comment]
> Although, Electron Builder did warn me about this:

@cyfrost I'm going to be looking into upgrading to Electron 6 again but the original problem we had was related to custom styles/preload scripts not working in windows opened with `window.open`.  I'll have to check and see if it is still a problem.

**Pull request merged**
