### PR TITLE
Fix new window header

### LINKED ISSUE #50: Mac "traffic lights" overlap content in new windows
When opening a new window or a notification, the Mac "traffic lights" overlap the content.

- Gmail Desktop Version: 2.4.0
- OS Version: macOS Mojave

Steps to Reproduce:

1. Hold down command/ctrl and click the compose button
2. Observe how the Mac "traffic lights" overlap the content

### PR DESCRIPTION
**Pull request by markypython**
Fixes #50

### CODE REVIEW

**Comment by markypython** [comment]
@bsramin I ended up just plowing through the last couple of styles.  Thanks for offering to help though.  We would certainly appreciate help on other issues!

**Comment by bsramin** [comment]
@markypython sorry for the wait, they are busy days at work, I'm back in business tomorrow

**Comment by markypython** [comment]
@bsramin Not a problem.  My week is not that busy so I thought I would push to get some stuff done on this project.

**Comment by markypython** [comment]
Also fixes #68

**Comment by timche** [comment]
Please merge this PR rebased to keep the commits and don't squash them as this PR does multiple things, not only the PR title.

> Rollback electron version

**Comment by markypython** [comment]
How would I go about changing that commit message?  Will I be able to do that during the rebase and merge?

**Comment by timche** [comment]
Unfortunately you can't rename the commits here, but you simply run `git rebase master --interactive` or just `-i` and select the commits you want to rename and then force-push `git push --force` or `git push --force-with-lease` which is a little more safe and helpful, when multiple people are working on a branch and to avoid overwriting the remote branch when it's newer.

**Comment by timche** [comment]
FYI: I needed to place `electron` back to `devDependencies`, because of:

```
$ tsc && electron-builder --macos --linux --windows --publish never
  • electron-builder version=20.38.5
  • loaded configuration file=package.json ("build" field)
Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.
error Command failed with exit code 1.
```

https://travis-ci.org/timche/gmail-desktop/builds/519847188

**Pull request merged**
