### PR TITLE
Close new window when email is archived, marked as spam, or deleted

### LINKED ISSUE #62: Close window on click "Archive" when email opened in new window
When opening an email via an notification, the email will be opened in a new window. It would be nice when clicking on "Archive" the window will be closed automatically. This is a behaviour I know from the Gmail app on iOS.

This could be made configurable.

### PR DESCRIPTION
**Pull request by markypython**
Fixes #62

### CODE REVIEW

**Comment by timche** [comment]
Follow up from #69:

---

**1. Testing Question:**

I tried to checkout this PR, but the buttons aren't working for me. Anything I'm missing? I used the "In new window" button to open an email in a new window.

image

---

**2. Discussion about using `element-ready` package instead of `setTimeout`:**

@markypython:
> So, I looked into the source of element-ready and it is using `requestAnimationFrame` to check if the element is present on the page.  This seems like overkill for what we need since that would be checking 60 times per second if the element is on the page.  I still think we should leave it as is, but if you disagree, let me know.

@timche
> I'm open to discuss the pros and cons. According to this [issue](https://github.com/sindresorhus/element-ready/issues/4), performance-wise it shouldn't be that CPU-intensive. Also using `setTimeout` can still leave a very small time-window open where the listener is not attached when clicked before, although the change might be quite low, but it can happen.

**Comment by markypython** [comment]
I refactored to use element-ready and added a 10 second safety net in case element-ready starts in a window that doesn't have the buttons we are looking for.  Additionally, I remove the spam button because it requires a prompt after clicking the button before the message is marked as spam.

**Comment by markypython** [comment]
> I tried to checkout this PR, but the buttons aren't working for me. Anything I'm missing? I used the "In new window" button to open an email in a new window.

I didn't notice this behavior.  Could you open a separate issue for this so we can discuss it futher?

**Comment by timche** [comment]
> I didn't notice this behavior. Could you open a separate issue for this so we can discuss it further?

Can you share a test plan just in case?

**Comment by markypython** [comment]
I tested on all platforms and it works fine.  Can you try reinstalling yarn packages?  This requires the electron downgrade from one of the other PRs so that might be the issue you are experiencing.

**Comment by timche** [comment]
I reinstalled all dependencies. Still doesn't work for me.

Can you share with me your test steps? Not sure if I'm just doing something wrong.

**Comment by markypython** [comment]
My testing steps were fairly simple.

1. Checkout the `close-new-window` branch
1. Run `yarn && yarn start`
1. Ctrl/cmd click on an email to open it in a new window
1. Click the archive or delete button and observe the new window being closed
1. Repeat 3-4 but using the open in new window button you showed in your screenshot

**Comment by markypython** [comment]
The two things you removed, `if (button) { ...` and the `setTimeout` were both added for strategic reasons which I will explain below.

*if button*

`document.querySelector` can return null and therefore having a check to verify the button is there is wise.  If Gmail selectors changed in the future, this would cause errors.  The likelihood that the selectors will change is probably almost nothing, so I would probably be okay with changing it to `button!.addEventListener`

*Timeout*

This one is more important in my opinion.  I Gmail url schemes change were our conditional no longer works exactly how we want it to, it could be possible for element ready to run in a window endlessly.  I'm of the opinion that the small bit of extra code for putting a safeguard like this in place is better than the possibility of creating a runaway check loop.  Yes, it might not be bad for performance, but running document.querySelector 60 times per second for 10 minutes might not be great for performance if such a case were to occur.

Thoughts?

**Comment by timche** [comment]
Thanks for sharing your thoughts!

---

**if button**

That would be solved waiting for each selector to be ready: `elementReady(`body.xE .G-atb .${selector}`)`

**Timeout**

Convinced.

---

I've added a timeout to my previous example:

```ts
function attachButtonListeners(): void {
  // For windows that won't include the selectors we are expecting,
  //   don't wait for them appear as they never will
  if (!window.location.search.includes('&search=inbox')) {
    return
  }

  const selectors = [
    'lR', // Archive
    'nX' // Delete
  ]

  selectors.forEach(async selector => {
    try {
      const buttonReady = elementReady(`body.xE .G-atb .${selector}`)

      const readyTimeout = setTimeout(() => {
        buttonReady.cancel(`Detect button "${selector}" timed out`)
      }, 10000)

      const button = await buttonReady
      clearTimeout(readyTimeout)

      button.addEventListener('click', () => window.close())
    } catch (err) {
      log.error(err)
    }
  })
}
```

My goal is to use  `async/await` instead of promise chaining to make the code more readable and modern. Additionally instead to wait for one button to access all others, wait for each button to make fully sure that it actually exists, so we don't have to double-check with `document.querySelector()` and `if (button)`. If one button timeouts, `cancel()` the promise and log the cancel error in the `catch` block.

**Comment by markypython** [comment]
Love the snippet you shared.  I'll get it updated today or tomorrow.

**Comment by markypython** [comment]
I updated with the changes you requested.

**Pull request merged**
