### PR TITLE
Fix/move google chat status menu

### PR DESCRIPTION
**Pull request by DinCahill**
The position of the Google Chat status dropdown is calculated in javascript. When compact header mode is enabled, it isn't positioned correctly, presumably because of the elements we've hidden.

They position it with the `top` and `left` properties, so I've used `transform: translateX(-100px)` to apply a constant offset.

Before:
before narrow
before wide
After:
fixed narrow
fixed wide
And when `<body dir='rtl'>`:
arabic

### CODE REVIEW

**Comment by DinCahill** [comment]
Something like this?
```css
:not([dir='rtl']).gmail-desktop_compact-header
  [style*='top:'][style*='left:'][style*='visibility:']
```

**Comment by timche** [comment]
As you're only targeting style values, I'm not 100% if this is unique enough. Are there any other attributes or paths you could use?

**Comment by DinCahill** [comment]
> As you're only targeting style values, I'm not 100% sure if this is unique enough. Are there any other attributes or paths you could use?

There are no other attributes. It has a single hardcoded Gmail class, so if we used that, the selector could just be `:not([dir='rtl']).gmail-desktop_compact-header .tP`.

**Comment by timche** [comment]
Thanks for explaining. 

Let's use the Gmail class instead, although it's not good, but safer, because `[style*='top:'][style*='left:'][style*='visibility:']` could also target another element with the same attributes.

**Review by timche — APPROVED** [review]

**Pull request merged**
