### PR TITLE
fix input tools in dark mode

### PR DESCRIPTION
**Pull request by DinCahill**
Settings > General > Language > Enable input tools

Please try this out and let me know what you think 🙂

### CODE REVIEW

**Comment by timche** [comment]
Could you provide screenshots please?

**Comment by DinCahill** [comment]
Before:
before ita dropdown
before ita list
before ita keyboard
before ita handwriting

After:
after ita dropdown
after ita list
after ita keyboard
after ita handwriting

On the handwriting panel, I'm not sure how to make the top-right X button look better. The top-left drag handle does invert nicely, so I will add a selector for that soon.

**Comment by DinCahill** [comment]
Drag handle:
after drag handle

**Comment by timche** [comment]
Thanks a lot for the screenshots! Great work!

**Pull request merged**
