### PR TITLE
New logo

### LINKED ISSUE #211: Update new Gmail logo
image

### PR DESCRIPTION
**Pull request by mskelton**
Fixes #211 

This PR adds the new gmail logo to the app.  I tested this on macOS and it looks good but I don't have a Windows or Linux device to test it on.

### CODE REVIEW

**Comment by timche** [comment]
Awesome stuff! Thanks for that.

We need to put some safe space around the icon:

Screen Shot 2020-11-02 at 17 44 37

Screen Shot 2020-11-02 at 17 44 41

Otherwise it will look like this in the dock:

Screen Shot 2020-11-02 at 17 43 33


While it normally looks like this:

Screen Shot 2020-11-02 at 17 45 23

To unblock the dependencies, can we split this PR please?

**Comment by mskelton** [comment]
How much space did you put around the logo for the old one?  I could eyeball it if you don't know

**Comment by timche** [comment]
Where did you get the logo from? I can edit it if you want.

**Comment by mskelton** [comment]
@timche  Here you go: https://1000logos.net/wp-content/uploads/2018/05/Gmail-logo-768x579.png

**Comment by timche** [comment]
Have updated the logo at df930fee3fcf44cc31620e4d03e3250bb21884f4 which also updated the Windows tray icon and macOS menu bar icon.

**Pull request closed without merging**
